# Netlify Configuration for SuperPage Frontend
# React/Vite application deployment configuration

[build]
  # Build command for Vite React app
  command = "npm run build"
  
  # Directory to publish (Vite default output)
  publish = "dist"
  
  # Base directory for build (frontend folder)
  base = "frontend"

[build.environment]
  # Node.js version
  NODE_VERSION = "18.19.0"
  
  # NPM version
  NPM_VERSION = "10.2.3"
  
  # Production environment
  NODE_ENV = "production"
  
  # Vite environment variables
  VITE_API_URL = "https://superpage-ingestion.onrender.com"
  VITE_PREDICTION_API_URL = "https://superpage-prediction.onrender.com"
  VITE_BLOCKCHAIN_API_URL = "https://superpage-blockchain.onrender.com"
  VITE_PREPROCESSING_API_URL = "https://superpage-preprocessing.onrender.com"

# Redirect rules for Single Page Application (SPA)
# All routes should serve index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# API proxy redirects (optional - for development)
[[redirects]]
  from = "/api/ingestion/*"
  to = "https://superpage-ingestion.onrender.com/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/api/prediction/*"
  to = "https://superpage-prediction.onrender.com/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/api/blockchain/*"
  to = "https://superpage-blockchain.onrender.com/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/api/preprocessing/*"
  to = "https://superpage-preprocessing.onrender.com/:splat"
  status = 200
  force = false

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CORS headers for API access
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, x-wallet-address"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Functions configuration (if using Netlify Functions)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Dev server configuration
[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  autoLaunch = false

# Build processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
