# Render Infrastructure as Code Configuration
# SuperPage - Real-time Decentralized Fundraise Prediction Agent
# Repository: https://github.com/mysticalseeker24/SuperPage

services:
  # Ingestion Service - Web3 Data Scraping via Firecrawl
  - type: web
    name: superpage-ingestion
    runtime: docker
    repo: https://github.com/mysticalseeker24/SuperPage.git
    branch: main
    dockerfilePath: ./backend/ingestion_service/Dockerfile
    dockerContext: ./backend/ingestion_service
    region: oregon
    plan: starter
    autoDeploy: true
    
    # Environment Variables
    envVars:
      - key: FIRECRAWL_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: DATABASE_URL
        fromDatabase:
          name: superpage-db
          property: connectionString
      - key: DATABASE_NAME
        value: superpage
      - key: SERVICE_NAME
        value: ingestion-service
      - key: SERVICE_VERSION
        value: 1.0.0
      - key: LOG_LEVEL
        value: INFO
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: WORKERS
        value: 4
      - key: FRONTEND_URL
        value: https://superpage-frontend.netlify.app

    # Health Check
    healthCheckPath: /health

  # Preprocessing Service - ML Feature Processing
  - type: web
    name: superpage-preprocessing
    runtime: docker
    repo: https://github.com/mysticalseeker24/SuperPage.git
    branch: main
    dockerfilePath: ./backend/preprocessing_service/Dockerfile
    dockerContext: ./backend/preprocessing_service
    region: oregon
    plan: starter
    autoDeploy: true
    
    # Environment Variables
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: superpage-db
          property: connectionString
      - key: DATABASE_NAME
        value: superpage
      - key: TOKENIZER_MODEL
        value: distilbert-base-uncased
      - key: MAX_TEXT_LENGTH
        value: 512
      - key: MAX_FEATURES
        value: 100
      - key: SCALER_TYPE
        value: minmax
      - key: SERVICE_NAME
        value: preprocessing-service
      - key: SERVICE_VERSION
        value: 1.0.0
      - key: LOG_LEVEL
        value: INFO
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: WORKERS
        value: 2
      - key: FRONTEND_URL
        value: https://superpage-frontend.netlify.app

    # Health Check
    healthCheckPath: /health

  # Prediction Service - ML Model Serving with SHAP
  - type: web
    name: superpage-prediction
    runtime: docker
    repo: https://github.com/mysticalseeker24/SuperPage.git
    branch: main
    dockerfilePath: ./backend/prediction_service/Dockerfile
    dockerContext: ./backend/prediction_service
    region: oregon
    plan: starter
    autoDeploy: true
    
    # Environment Variables
    envVars:
      - key: MODEL_PATH
        value: /app/models/latest/fundraising_model.pth
      - key: SCALER_PATH
        value: /app/models/latest/scaler.pkl
      - key: SHAP_BACKGROUND_SAMPLES
        value: 100
      - key: SERVICE_NAME
        value: prediction-service
      - key: SERVICE_VERSION
        value: 1.0.0
      - key: LOG_LEVEL
        value: INFO
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: WORKERS
        value: 2
      - key: FRONTEND_URL
        value: https://superpage-frontend.netlify.app

    # Health Check
    healthCheckPath: /health

  # Blockchain Service - Smart Contract Integration
  - type: web
    name: superpage-blockchain
    runtime: docker
    repo: https://github.com/mysticalseeker24/SuperPage.git
    branch: main
    dockerfilePath: ./backend/blockchain_service/Dockerfile
    dockerContext: ./backend/blockchain_service
    region: oregon
    plan: starter
    autoDeploy: true
    
    # Environment Variables
    envVars:
      - key: BLOCKCHAIN_PRIVATE_KEY
        sync: false  # Set manually in Render dashboard (sensitive)
      - key: SUPERPAGE_CONTRACT_ADDRESS
        value: 0x45341d82d59b3C4C43101782d97a4dBb97a42dba
      - key: BLOCKCHAIN_NETWORK_URL
        sync: false  # Set manually (Sepolia Infura URL)
      - key: SEP_RPC_URL
        sync: false  # Set manually (Sepolia RPC URL)
      - key: HARDHAT_PROJECT_PATH
        value: ./
      - key: GAS_LIMIT
        value: 500000
      - key: GAS_PRICE
        value: 20000000000
      - key: INFURA_PROJECT_ID
        sync: false  # Set manually in Render dashboard
      - key: ETHERSCAN_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: FRONTEND_URL
        value: https://superpage-frontend.netlify.app

    # Health Check
    healthCheckPath: /health

# Database Configuration - Render PostgreSQL
databases:
  - name: superpage-db
    databaseName: superpage
    user: superpage_user
    region: oregon
    plan: starter

# Static Site for Frontend (optional)
# - type: static
#   name: superpage-frontend
#   runtime: static
#   repo: https://github.com/mysticalseeker24/SuperPage.git
#   branch: main
#   buildCommand: cd frontend && npm install && npm run build
#   staticPublishPath: ./frontend/dist
#   region: oregon
#   autoDeploy: true
#   
#   envVars:
#     - key: VITE_API_URL
#       value: https://superpage-ingestion.onrender.com
#     - key: NODE_ENV
#       value: production

# Redis Cache (optional for future scaling)
# - type: redis
#   name: superpage-cache
#   region: oregon
#   plan: starter
#   maxmemoryPolicy: allkeys-lru
